[package]
name = "kyotocabinet-sys"
version = "0.2.0"
authors = ["IDA Kenichiro <ida.kenichiro@gmail.com>"]
description = "libkyotocabinet bindings for Rust."
license = "MIT"
edition = "2018"

[build-dependencies]
