[package]
name = "kyotocabinet-sys"
version = "0.1.0"
authors = ["Kenichiro IDA <ida.kenichiro@gmail.com>"]
description = "libkyotocabinet bindings for Rust."
license = "MIT"
edition = "2018"

[build-dependencies]
bindgen = "*"
